# Generated by Django 3.2.4 on 2021-12-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='images')),
                ('name', models.CharField(max_length=50)),
                ('game', models.CharField(max_length=250)),
            ],
        ),
    ]
