# Generated by Django 3.2.4 on 2021-12-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_playgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.FileField(upload_to='')),
                ('image', models.ImageField(default=None, upload_to='images')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
