# Generated by Django 3.2.10 on 2022-02-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamefile', models.FileField(upload_to='media')),
                ('image', models.ImageField(default=None, upload_to='images')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
    ]
