# Generated by Django 3.2.10 on 2022-02-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AlterField(
            model_name='download',
            name='game',
            field=models.FileField(upload_to='media'),
        ),
    ]
